name: jap_logger

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy
  - pandas
  - plotly
  - matplotlib=3.6
  - protobuf=3.20
  - streamlit
  - black
  - pip
  - pip:
    - july
    - st-theme
    - plotly-calplot